### ISSUE TITLE
Dont work on test branch

### ISSUE THREAD

**Issue by OmiSingh2004** [OmiSingh2004/JPetBot#3]
Dear EdanTuti,
How are you? Hows life and business? Hope you are studying well. blablabla
This is to inform you that i have changed the branch name from test -> dont work on this bro
hope you know what it means
hope i know what it means
hope we dont mess up and WORK ON TEST1 ONLY
and once we are sure that this system is tight, we will pull request to master and booom, we gucci

**Comment by Edantuti** [comment]
Okey, I will look forward into that

**Comment by Edantuti** [comment]
Delete the branch
